---

- name: Tune sysctl
  sysctl:
    name: "{{ item.name  }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    sysctl_set: true
    reload: true
  with_items: "{{ sysctl_antiddos }}"
