---
# tasks file for sysctl_tune
- name: Tune sysctl
  sysctl:
    name: "{{ item.name  }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "vm.swappiness", value: 5, state: present }
    - { name: "net.ipv4.tcp_max_orphans", value: 65536, state: present }
    ##Рекомендуется увеличить размер backlog до 1000 или выше (для 10Gb линка можно поставить 30000)
    - { name: "net.core.netdev_max_backlog", value: 10000, state: present }
    ##Переменная определяет максимальное время хранения SYN-запросов в памяти до момента получения третьего, завершающего установление соединения, пакета
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 131072, state: present }
    ##Максимальное число сокетов, находящихся в состоянии TIME-WAIT одновременно. При превышении этого порога «лишний» сокет разрушается и пишется сообщение в системный журнал. Цель этой переменной – предотвращение простейших разновидностей DoS-атак.
    - { name: "net.ipv4.tcp_max_tw_buckets", value: 720000, state: present }
    - { name: "net.ipv4.tcp_tw_reuse", value: 1, state: present } 
    - { name: "net.ipv4.tcp_tw_recycle", value: 1, state: present }
    - { name: "net.ipv4.tcp_fin_timeout", value: 30, state: present }
    - { name: "net.ipv4.tcp_keepalive_time", value: 1800, state: present }
    - { name: "net.ipv4.tcp_keepalive_probes", value: 7, state: present }
    - { name: "net.ipv4.tcp_keepalive_intvl", value: 30, state: present }
    ##Размер буферов по умолчанию для приема и отправки данных через сокеты
    - { name: "net.core.wmem_default", value: 4194394, state: present }
    - { name: "net.core.rmem_default", value: 8388608, state: present }
    ##Увеличиваем максимальный размер памяти отводимой для TCP буферов
    - { name: "net.core.wmem_max", value: 33554432, state: present }
    - { name: "net.core.rmem_max", value: 33554432, state: present }
    ##буфер для TCP и UDP соединений (min, default, max bytes)
    - { name: "net.ipv4.tcp_rmem", value: 4096 8388608 16777216, state: present }
    - { name: "net.ipv4.tcp_wmem", value: 4096 4194394 16777216, state: present }
    - { name: "vm.dirty_ratio", value: 60, state: present }
    - { name: "vm.dirty_background_ratio", value: 2, state: present }
    - { name: "net.ipv4.tcp_syn_retries", value: 3, state: present }
    - { name: "net.ipv4.tcp_synack_retries", value: 3, state: present }
    - { name: "net.ipv4.tcp_retries1", value: 3, state: present }
    - { name: "net.ipv4.tcp_retries2", value: 8, state: present }
    - { name: "net.ipv4.tcp_mem", value: 262144 524288 1048576, state: present }
    - { name: "net.ipv4.tcp_low_latency", value: 1, state: present }
    - { name: "net.ipv4.tcp_syncookies", value: 0, state: present }
    - { name: "net.netfilter.nf_conntrack_max", value: 1048576, state: present }

